use <library.scad>
include <global_parameters.scad>

$fn = 50;

translate([0, 0, KINDERJOINT_HEIGHT + CLEARENCE]) pcb_holder_supports(50, 45 + CLEARENCE, 1 + CLEARENCE, 4, WALL_TH, WALL_TH, RADIUS, 5);

translate([0, 0, STAGE_HEIGHT - KINDERJOINT_HEIGHT]) tube(WALL_TH, RADIUS - WALL_TH, NOSECONE_JOINT_HEIGHT + 10);
translate([0, 0, KINDERJOINT_HEIGHT]) tube(WALL_TH, RADIUS, STAGE_HEIGHT - KINDERJOINT_HEIGHT - NOSECONE_JOINT_HEIGHT);
kinderjoint_f(RADIUS, KINDERJOINT_HEIGHT, KINDERJOINT_BALL_R, KINDERJOINT_BALL_TH, WALL_TH);